name: codspeed-benchmarks

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH  # Ensures uv is on PATH if installed via cargo

      - name: Setup Python (just for tooling, uv handles env)
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies with uv
        run: |
          uv pip install pytest pytest-cov pytest-codspeed
          uv pip install -e .

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          # token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest . --codspeed
